name = "api"
main = "src/index.ts"
compatibility_date = "2025-01-10"
assets = { directory = "public" }

# [placement]
# mode = "smart"
# node_compat = true

compatibility_flags = ["nodejs_compat"]

[vars]
MY_VAR = "my-variable"

[[d1_databases]]
binding = "DB"
database_name = "tellapp-db"
database_id = "d0b07f27-00ed-426d-8ae4-692e970da855"
migrations_dir = "./migrations"

[observability.logs]
enabled = true


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
